# Site settings
title: Tutorial: proyecto de retención U de Londres
email: alberto@foris.ai
description: "Tutorial: proyecto de retención U de Londres."
twitter_username: acrendic
github_username:  lacrendic	# Build settings
markdown: kramdown
permalink: pretty	
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
