# Site settings
title: "Tutorial: U de Londres Retention Project"
email: alberto@foris.ai
description: "Tutorial: U de Londres."
twitter_username: acrendic
github_username:  lacrendic

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
